services:
  - type: web
    name: mabinogi-party
    env: python
    pythonVersion: 3.11
    buildCommand: "apt-get update && apt-get install -y chromium-browser && apt-get install -y chromium-driver && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: PARTY_SITE_URL
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
